
module.exports = [

    {
        nombre: 'Rosa rugosa',
        precio: 35000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/rosaRugosa.png', 'images/rosaRugosa1.png', 'images/rosaRugosa2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 15,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '10 días',
        rango: '30 COP - 45 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Rosa Rugosa es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',
    },

    {
        nombre: 'Arum',
        precio: 25000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/arum.png', 'images/arum1.png', 'images/arum2.png' ],
        categoria: 'flores',
        tipo: 'arums',
        altura: 30,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '20 días',
        rango: '15 COP - 30 COP',
        genero: 'Phalaenopsis',
        descripcion: 'El Arum es empleado principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },


    {
        nombre: 'Astilbe Blanca',
        precio: 62000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/astilbeBlanca.png', 'images/astilbeBlanca1.png', 'images/astilbeBlanca2.png' ],
        categoria: 'flores',
        tipo: 'astilbes',
        altura: 20,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '12 días',
        rango: '60 COP - 75 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Astilbe Blanca es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Celidonia',
        precio: 40000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/celidonia.png', 'images/celidonia1.png', 'images/celidonia2.png' ],
        categoria: 'flores',
        tipo: 'celidonias',
        altura: 12,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '25 días',
        rango: '30 COP - 45 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Celidonia es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    
    {
        nombre: 'Dalia',
        precio: 50000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/dalia.png', 'images/dalia1.png', 'images/dalia2.png' ],
        categoria: 'flores',
        tipo: 'dalias',
        altura: 18,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '15 días',
        rango: '45 COP - 60 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Dalia es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Dalia Blanca',
        precio: 55000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/daliaBlanca.png', 'images/daliaBlanca1.png', 'images/daliaBlanca2.png' ],
        categoria: 'flores',
        tipo: 'dalias',
        altura: 20,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '13 días',
        rango: '45 COP - 60 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Dalia Blanca es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Eustoma',
        precio: 65000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/eustoma.png', 'images/eustoma1.png', 'images/eustoma2.png' ],
        categoria: 'flores',
        tipo: 'eustomas',
        altura: 40,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '20 días',
        rango: '60 COP - 75 COP',
        genero: 'Phalaenopsis',
        descripcion: 'El Eustoma es empleado principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Jazmín',
        precio: 78000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/jazmin.png', 'images/jazmin1.png', 'images/jazmin2.png' ],
        categoria: 'flores',
        tipo: 'jazmines',
        altura: 70,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '30 días',
        rango: '75 COP - 99 COP',
        genero: 'Phalaenopsis',
        descripcion: 'El Jazmín es empleado principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Orquídea Blanca',
        precio: 100000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/orquideaBlanca.png', 'images/orquideaBlanca1.png', 'images/orquideaBlanca2.png' ],
        categoria: 'flores',
        tipo: 'orquideas',
        altura: 25,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '25 días',
        rango: '100 COP +',
        genero: 'Phalaenopsis',
        descripcion: 'La Orquídea Blanca es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Peonía Roja',
        precio: 80000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/peonia.png', 'images/peonia1.png', 'images/peonia2.png' ],
        categoria: 'flores',
        tipo: 'peonías',
        altura: 30,
        color: 'rojo',
        duracion: '15 días',
        rango: '75 COP - 99 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Peonía Roja es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Peonía Salmón',
        precio: 95000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/peoniaSalmon.png', 'images/peoniaSalmon1.png', 'images/peoniaSalmon2.png' ],
        categoria: 'flores',
        tipo: 'peonías',
        altura: 35,
        color: 'salmon',
        duracion: '12 días',
        rango: '75 COP - 99 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Peonía Salmón es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Peonía Violeta',
        precio: 90000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/peoniaVioleta.png', 'images/peoniaVioleta1.png', 'images/peoniaVioleta2.png' ],
        categoria: 'flores',
        tipo: 'peonías',
        altura: 50,
        color: 'violeta',
        duracion: '17 días',
        rango: '75 COP - 99 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Peonía Violeta es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Peonía Blanca',
        precio: 56000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/peoniaBlanca.png', 'images/peoniaBlanca1.png', 'images/peoniaBlanca2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 30,
        color: 'blanco',
        duracion: '10 días',
        rango: '45 COP - 60 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Peonía Blanca es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },


    {
        nombre: 'Ranúnculo',
        precio: 55000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/ranunculoRosa.png', 'images/ranunculoRosa1.png', 'images/ranunculoRosa2.png' ],
        categoria: 'flores',
        tipo: 'ranúnculos',
        altura: 50,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '17 días',
        rango: '45 COP - 60 COP',
        genero: 'Phalaenopsis',
        descripcion: 'El Ranúnculo es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },


    {
        nombre: 'Rosa Combinada',
        precio: 30000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/rosaCombinada.png', 'images/rosaCombinada1.png', 'images/rosaCombinada2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 15,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '8 días',
        rango: '30 COP - 45 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Rosa Combinada es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',


    },

    {
        nombre: 'Rosa Común',
        precio: 28000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/rosaComun.png', 'images/rosaComun1.png', 'images/rosaComun2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 13,
        color: ['rosa', 'blanco', 'rojo'],
        duracion: '5 días',
        rango: '15 COP - 30 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Rosa Común es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Rosa Jardín',
        precio: 33000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/rosaJardin.png', 'images/rosaJardin1.png', 'images/rosaJardin2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 13,
        color: ['rosa', 'blanco', 'rojo','amarillo'],
        duracion: '7 días',
        rango: '30 COP - 45 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Rosa de Jardín es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Rosa Julieta',
        precio: 25000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/rosaJulieta.png', 'images/rosaJulieta1.png', 'images/rosaJulieta2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 12,
        color: ['rosa', 'blanco', 'rojo','amarillo'],
        duracion: '4 días',
        rango: '15 COP - 30 COP',

    },

    {
        nombre: 'Rosa Rugosa Roja',
        precio: 43000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/rosaRugosaRoja.png', 'images/rosaRugosaRoja1.png', 'rosaRugosaRoja2.png' ],
        categoria: 'flores',
        tipo: 'rosas',
        altura: 15,
        color: 'rojo',
        duracion: '7 días',
        rango: '30 COP - 45 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Rosa Julieta es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

    {
        nombre: 'Verbena',
        precio: 40000,
        etiqueta: '15% OFF',
        like: false,
        imagen: ['images/verbena.png', 'images/verbena1.png', 'verbena2.png' ],
        categoria: 'flores',
        tipo: 'verbenas',
        altura: 35,
        color: ['rosa', 'blanco', 'rojo','amarillo'],
        duracion: '15 días',
        rango: '30 COP - 45 COP',
        genero: 'Phalaenopsis',
        descripcion: 'La Verbena es empleada principalmente como ornamental por su buen porte y la belleza de sus flores y pétalos. Posee cortas espinas, tallos robustos y fasciculados.',
        cuidados: '  Debe recibir luz solar directa cada 5 a 6 horas. Regar de 2 a 3 veces por semana en la mañana o en la tarde.',
        floracion: '2 a 4 meses',

    },

];